sonar.projectKey=linguanova
sonar.projectName=LinguaNova
sonar.sourceEncoding=UTF-8

sonar.sources=LinguaNova/src,backend/microservices
sonar.tests=LinguaNova/src,backend/microservices
sonar.test.inclusions=**/*.spec.ts,**/*Test.java,**/*Tests.java

sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/.angular/**,**/.mvn/**,**/mvnw,**/mvnw.cmd
sonar.javascript.lcov.reportPaths=LinguaNova/coverage/lcov.info
